"""
Inject Imagen-generated images into Claude-converted HTML
---------------------------------------------------------
The HTML produced by `shared/claude_html_converter.py` may contain
`[[IMAGE: <english prompt>]]` markers placed by Claude per the
~/.claude/skills/blogger-html/SKILL.md instruction. This module:

    1. Scans the HTML for markers (re.findall)
    2. For each marker:
         a. Generates image via Imagen (shared.image_generator)
         b. Uploads to Cloudinary (shared.image_uploader) → public URL
         c. Replaces marker with `<img src="URL" alt="..." loading="lazy" />`
    3. Returns the injected HTML

If credentials are missing or generation fails, the marker is replaced with
a comment `<!-- IMAGE GEN FAILED: <reason> -->` so the post still publishes.
Failure does not block the upload pipeline.

Usage in bot:
    from shared.claude_html_converter import convert_md_to_html_via_claude
    from shared.blogger_html_inject import inject_images

    html, title = convert_md_to_html_via_claude(markdown)
    html = inject_images(html, run_id="news_2026-05-28")
    blogger_uploader.upload_post(title=title, content=html, ...)
"""

from __future__ import annotations

import logging
import os
import re
from dataclasses import dataclass, field
from typing import List, Optional

logger = logging.getLogger(__name__)


# Marker format: [[IMAGE: <english prompt>]]  or  [[IMAGE:<english prompt>]]
# Greedy enough to capture multi-line prompts but stops at `]]`.
IMAGE_MARKER_RE = re.compile(r"\[\[IMAGE\s*:\s*(.+?)\s*\]\]", re.DOTALL)

# Default max images per post (cost / Imagen quota guard).
# 25 RPD per model × 3 models = 75/day total. With ~10 posts/day,
# 3 images/post is the comfortable ceiling.
DEFAULT_MAX_IMAGES = int(os.getenv("BLOGGER_MAX_IMAGES_PER_POST", "3"))


@dataclass
class InjectStats:
    markers_found: int = 0
    images_generated: int = 0
    images_uploaded: int = 0
    skipped_over_cap: int = 0
    failed: int = 0
    failures: List[str] = field(default_factory=list)


def inject_images(
    html: str,
    run_id: str,
    *,
    aspect_ratio: str = "16:9",
    max_images: int = DEFAULT_MAX_IMAGES,
    folder: Optional[str] = None,
) -> tuple[str, InjectStats]:
    """Replace [[IMAGE:...]] markers in HTML with `<img>` tags.

    Args:
        html: Claude-converted HTML containing zero or more markers.
        run_id: stable identifier (e.g. 'news_2026-05-28', 'telegram_1628').
            Used as Cloudinary public_id prefix for grouping.
        aspect_ratio: forwarded to Imagen. Default 16:9 (blog-friendly).
        max_images: cap to protect Imagen daily quota. Markers beyond cap
            are replaced with a stub HTML comment.
        folder: Cloudinary folder override. Default: '006_auto_bot/<run_id_prefix>'.

    Returns:
        (injected_html, stats)
    """
    from shared.image_generator import generate_image, ImagenError
    from shared.image_uploader import upload_to_cdn, CloudinaryError

    stats = InjectStats()
    matches = list(IMAGE_MARKER_RE.finditer(html))
    stats.markers_found = len(matches)

    if not matches:
        return html, stats

    logger.info(f"inject_images: {len(matches)} markers found, cap={max_images}")

    # Walk matches and build replacements; we replace by index to keep
    # offsets stable across the iteration.
    new_html_parts: List[str] = []
    last_end = 0

    # Cloudinary subfolder per run (keeps organization clean).
    bot_folder = folder or f"006_auto_bot/{_safe_run_id(run_id)}"

    for idx, m in enumerate(matches, start=1):
        new_html_parts.append(html[last_end:m.start()])

        if idx > max_images:
            stats.skipped_over_cap += 1
            new_html_parts.append(
                f"<!-- IMAGE skipped (max_images={max_images} cap) -->"
            )
            logger.info(f"  marker {idx}: skipped (over cap)")
            last_end = m.end()
            continue

        prompt = m.group(1).strip()
        if not prompt:
            stats.failed += 1
            stats.failures.append("empty prompt")
            new_html_parts.append("<!-- IMAGE skipped (empty prompt) -->")
            last_end = m.end()
            continue

        public_id = f"img_{idx}"

        # Step 1: generate
        try:
            img = generate_image(prompt, aspect_ratio=aspect_ratio)
            stats.images_generated += 1
            logger.info(
                f"  marker {idx}: generated bytes={len(img.image_bytes)} "
                f"model={img.model_used}"
            )
        except ImagenError as e:
            stats.failed += 1
            stats.failures.append(f"imagen[{idx}]: {e}")
            new_html_parts.append(f"<!-- IMAGE GEN FAILED: {_html_escape(str(e))} -->")
            last_end = m.end()
            continue

        # Step 2: upload
        try:
            result = upload_to_cdn(
                img.image_bytes,
                public_id=public_id,
                folder=bot_folder,
                format="webp",
            )
            stats.images_uploaded += 1
            logger.info(f"  marker {idx}: uploaded url={result.secure_url[:80]}")
        except CloudinaryError as e:
            stats.failed += 1
            stats.failures.append(f"cloudinary[{idx}]: {e}")
            new_html_parts.append(f"<!-- IMAGE UPLOAD FAILED: {_html_escape(str(e))} -->")
            last_end = m.end()
            continue

        # Step 3: replace marker with <img>
        alt = _html_escape(prompt[:120])
        img_tag = (
            f'<img src="{result.secure_url}" alt="{alt}" '
            f'loading="lazy" width="{result.width}" height="{result.height}" '
            f'style="max-width:100%;height:auto;border-radius:8px;margin:16px 0;" />'
        )
        new_html_parts.append(img_tag)
        last_end = m.end()

    new_html_parts.append(html[last_end:])
    injected = "".join(new_html_parts)

    logger.info(
        f"inject_images done: markers={stats.markers_found} "
        f"generated={stats.images_generated} uploaded={stats.images_uploaded} "
        f"skipped={stats.skipped_over_cap} failed={stats.failed}"
    )
    return injected, stats


def _safe_run_id(run_id: str) -> str:
    """Sanitize run_id for use as Cloudinary folder path."""
    return re.sub(r"[^a-zA-Z0-9_/-]", "_", run_id)[:80]


def _html_escape(text: str) -> str:
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )
